### ISSUE TITLE
Link to Minigo v5-19x19 games

### ISSUE THREAD

**Issue by sethtroisi** [yenw/computer-go-dataset#3]
https://console.cloud.google.com/storage/browser/minigo-pub/v5-19x19/sgf/archives/

**Comment by yenw** [comment]
Thanks.

**Comment by sethtroisi** [comment]
It's not a <dataset> but you could consider adding a link to the my unofficial Minigo Game Viewer [cloudygo.com](cloudygo.com) which is nice you want to look at just a couple of Minigo games

**Comment by yenw** [comment]
I want to make a suggestion. Can you add some details(simulations, blocks, filters, fpu, c_puct, etc) of the model?
Otherwise we don't know the difference between v3, v5, v7 and v9.

I only know is that the v3 is 9blocks x 32filters and v7a is 20blocks x 128filters.
And the v9 is trained in the AlphaZero method.

**Comment by sethtroisi** [comment]
Yes; I'm not sure where I'll put it but I'l add those details soon.

**Comment by sethtroisi** [comment]
Some of this data is at https://cloudygo.com/RESULTS

**Comment by sethtroisi** [comment]
And https://github.com/tensorflow/minigo/blob/master/RESULTS.md

but more work to make these details clear needs to be done.

**Comment by yenw** [comment]
Thanks.

By the way,  
v3 is 9blocks x 32filters, 
v7 is 19blocks x 128filters,
v9/v10/v12 is 19blocks x 256filters.

The "blocks" means res-blocks.
